### PR TITLE
Update to 0.20.6

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Quick question. How important is the OS X dependency on `gnureadline`? If we can drop that we can build this as `noarch` in a single CircleCI instance.

**Comment by blink1073** [comment]
I'm not sure, it looks like you added it here: https://github.com/conda-forge/metakernel-feedstock/pull/2/files.

**Comment by ocefpaf** [comment]
I don't recall the reason but look into those changes it seems that when we removed homebrew packages from the Travis-CI image the build broken and I had to re-add `gnureadline`. I'll experiment without that to see if we can build without it. (A lot has changed since then.)

**Comment by ocefpaf** [comment]
It seems that we can remove `gnureadline` based on my [test](https://travis-ci.org/ocefpaf/metakernel-feedstock/builds/272515230). I'll try to use the `noarch` here then.

**Comment by ocefpaf** [comment]
Using `noarch` is much better! Build complete!!

**Comment by blink1073** [comment]
Nice!

**Pull request merged**
