### PR TITLE
[ci skip] [cf admin skip] ***NO_CI*** adding bot automerge

### LINKED ISSUE #47: @conda-forge-admin,please add bot automerge
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added bot automerge as instructed in #47.

Merge this PR to enable bot automerging.

Fixes #47

### CODE REVIEW

**Comment by blink1073** [comment]
Not sure what to make of the failure:

```
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/b1282e52-71d6-4f6a-9ee7-fa9ac378f58f.sh

/home/vsts/work/_temp/b1282e52-71d6-4f6a-9ee7-fa9ac378f58f.sh: line 3: .azure-pipelines/run_docker_build.sh: No such file or directory
##[error]Bash exited with code '127'.
Finishing: Run docker build
```

**Comment by blink1073** [comment]
cc @conda-forge/core

**Comment by beckermr** [comment]
Note that you can merge this one without the CI passing. It won't actually rebuild the package on master due to the ci skip. statements.

**Comment by blink1073** [comment]
Understood, thanks @beckermr!

**Pull request merged**
