### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by henryiii**
Running kernels in Jupyter that depend on this (like ROOT) break due to this missing dependency.

```
[IPKernelApp] ERROR | Can't load '/usr/local/miniconda3/envs/myroot/lib/python3.7/site-packages/metakernel/magics/parallel_magic.py': error: No module named 'ipyparallel'
```

See https://github.com/Calysto/metakernel/blob/master/setup.py

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
Conda-forge linter recommends that we change the line:

```
python setup.py install --single-version-externally-managed --record record.txt
```

to:
```
 "{{ PYTHON }} -m pip install . --no-deps -vv"
```

Along with adding pip to the host requirements. I can add that to this PR if you want me to.

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
Yes, please do

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Cheers!

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
Okay, that should be good if everything passes.

**Pull request merged**
