### PR TITLE
Bump to 0.17.2

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@blink1073 do you mind re-rendering so we can get Python 3.6 here?

**Comment by blink1073** [comment]
It looks like one or more upstream dependencies are not built on Python 3.6 yet.

**Comment by mariusvniekerk** [comment]
Probably worthwhile figuring what they are.

**Comment by blink1073** [comment]
Looks like `jupyter*` and `pexpect`.

**Comment by blink1073** [comment]
Oh, and gnureadline (so all of them).

**Comment by mariusvniekerk** [comment]
yeah, probably too much pain then to wait for all that to get built

**Comment by ocefpaf** [comment]
I can tackle the remaining packages later today. But if you don't want to
wait just revert the PY36 change.

On Jan 7, 2017 1:57 PM, "Marius van Niekerk" <notifications@github.com>
wrote:

yeah, probably too much pain then to wait for all that to get built

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/metakernel-feedstock/pull/14#issuecomment-271095306>,
or mute the thread

**Comment by blink1073** [comment]
No rush, I'll leave this open and let me know if you want me to re-smithy or you can merge this as-is without the 3.6 support.

**Comment by ocefpaf** [comment]
I submitted `pexpect` in https://github.com/conda-forge/pexpect-feedstock/pull/7
`gnureadline` is not needed.
I will start submitting `jupyter-*` now but we do not have the `jupyter` metapackage in `conda-forge`.
I am not sure if we could change it here to depend only on `jupyter-core`?

**Comment by blink1073** [comment]
It looks like `ipykernel` has everything we're basing ourselves on based on looking at our code (except `pexpect`): https://github.com/conda-forge/ipykernel-feedstock/blob/master/recipe/meta.yaml

**Pull request merged**
